https://docs.scipy.org/doc/numpy-1.13.0/reference/index.html

http://scipy-cookbook.readthedocs.io/items/Indexing.html

http://www.labri.fr/perso/nrougier/from-python-to-numpy/

In [3]:
import numpy as np

### Creating vectors
```python
np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
np.arange([start,] stop[, step,], dtype=None)
```

### Creating matrices
```python
np.arange(9).reshape(3,3).astype(np.int16)
np.zeros(shape, dtype=float, order='C')
np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
np.full(shape, fill_value, dtype=None, order='C')

x, y = np.mgrid[0:10:.1, 0:10:.2]

matA.repeat(repeats, axis=None) # normally chose axis=1/2
matA.repeat(1, axis=None) # flatten method 1
np.matrix.flatten(matA) # flatten method 2

```

### Selecting/Indexing
```python
matA.shape
matA.ndim
vec.argmax()
mat.argmin()
for i in np.ndindex(B.shape):
    print (i, B[i])
```

### Views/Slices and Copies
```python
ss = s[::2,::2]
Z_view = Z[:5]; Z_view[...] = 1
Z_copy = Z[[0,1,2]]; Z_copy[...] = 1
```

### Math
```python
matA = dot(matB, matC)
```

In [42]:
a = np.array([[0, 1], [2, 3]])
a.repeat(2, axis=0)) # repeats each row twice in succession


[[0 1]
 [0 1]
 [2 3]
 [2 3]]


In [43]:
print(a.repeat(1, axis=None))

[0 1 2 3]


In [44]:
a

array([[0, 1],
       [2, 3]])

In [48]:
b=np.matrix.flatten(a)

In [49]:
b

array([0, 1, 2, 3])