https://docs.scipy.org/doc/numpy-1.13.0/reference/index.html

http://scipy-cookbook.readthedocs.io/items/Indexing.html

http://www.labri.fr/perso/nrougier/from-python-to-numpy/

In [3]:
import numpy as np

### Creating vectors
```python
np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
np.arange([start,] stop[, step,], dtype=None)
np.random.randint(low, high=None, size=None, dtype='l')
```

### Creating matrices
```python
np.arange(9).reshape(3,3).astype(np.int16)
np.zeros(shape, dtype=float, order='C')
np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
np.full(shape, fill_value, dtype=None, order='C')

x, y = np.mgrid[0:10:.1, 0:10:.2]

matA.repeat(repeats, axis=None) # normally chose axis=1/2
matA.repeat(1, axis=None) # flatten method 1
np.matrix.flatten(matA) # flatten method 2

```

### Selecting/Indexing
```python
matA.shape
matA.ndim
vec.argmax()
mat.argmin()
for i in np.ndindex(B.shape):
    print (i, B[i])
```

### Views/Slices and Copies
```python
ss = s[::2,::2]
Z_view = Z[:5]; Z_view[...] = 1
Z_copy = Z[[0,1,2]]; Z_copy[...] = 1
```

### Math
```python
matA = dot(matB, matC)
matA.std()
matA.sum(axis=None, dtype=None, out=None, keepdims=False)
```

In [79]:
matA = np.random.randint(1,101, 10).reshape(2,5)
matA

array([[25, 64,  4, 44, 45],
       [95, 34, 53, 23, 68]])

In [84]:
matA[1,::-1]

array([68, 23, 53, 34, 95])

In [85]:
b = matA.T

b

In [87]:
b[::-1]

array([[45, 68],
       [44, 23],
       [ 4, 53],
       [64, 34],
       [25, 95]])

In [74]:
matA.sum(axis =0)

array([121, 119, 110,  66,  89])

In [75]:
print(matA.repeat(1, axis=None)[::-1])


[55 47 41 50 83 34 19 69 69 38]
