https://docs.scipy.org/doc/numpy-1.13.0/reference/index.html

http://scipy-cookbook.readthedocs.io/items/Indexing.html

http://www.labri.fr/perso/nrougier/from-python-to-numpy/

In [3]:
import numpy as np

### Creating vectors
```python
np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
np.arange([start,] stop[, step,], dtype=None)
np.random.randint(low, high=None, size=None, dtype='l')
```

### Creating matrices
```python
np.arange(9).reshape(3,3).astype(np.int16)
np.zeros(shape, dtype=float, order='C')
np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
np.full(shape, fill_value, dtype=None, order='C')

x, y = np.mgrid[0:10:.1, 0:10:.2]

matA.repeat(repeats, axis=None) # normally chose axis=1/2
matA.repeat(1, axis=None) # flatten method 1
np.matrix.flatten(matA) # flatten method 2

```

### Selecting/Indexing
```python
matA.shape
matA.ndim
vec.argmax()
mat.argmin()
for i in np.ndindex(B.shape):
    print (i, B[i])
```

### Views/Slices and Copies
```python
ss = s[::2,::2]
Z_view = Z[:5]; Z_view[...] = 1
Z_copy = Z[[0,1,2]]; Z_copy[...] = 1
```

### Math
```python
matA = dot(matB, matC)
matA.std()
matA.sum(axis=None, dtype=None, out=None, keepdims=False)
```

In [4]:
matA = np.random.randint(1,101, 10).reshape(2,5)
matA

array([[82, 78, 38, 14, 68],
       [67, 74,  6,  9, 30]])

In [5]:
matA[1,::-1]

array([30,  9,  6, 74, 67])

In [6]:
b = matA.T

b

In [7]:
b[::-1]

array([[68, 30],
       [14,  9],
       [38,  6],
       [78, 74],
       [82, 67]])

In [8]:
matA.sum(axis =0)

array([149, 152,  44,  23,  98])

In [12]:
x, y = np.mgrid[0:10:.1, 0:10:.2]
y

array([[0. , 0.2, 0.4, ..., 9.4, 9.6, 9.8],
       [0. , 0.2, 0.4, ..., 9.4, 9.6, 9.8],
       [0. , 0.2, 0.4, ..., 9.4, 9.6, 9.8],
       ...,
       [0. , 0.2, 0.4, ..., 9.4, 9.6, 9.8],
       [0. , 0.2, 0.4, ..., 9.4, 9.6, 9.8],
       [0. , 0.2, 0.4, ..., 9.4, 9.6, 9.8]])

In [10]:
print(matA.repeat(1, axis=None)[::-1])

[30  9  6 74 67 68 14 38 78 82]


In [ ]:
x, y = np.mgrid[0:10:.1, 0:10:.2]

In [16]:
np.tile(2, (5,3))

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [19]:
np.repeat([1,2], (5,2))

array([1, 1, 1, 1, 1, 2, 2])