In [14]:
import numpy

In [23]:
def random_walk(n):
    steps = np.random.choice([-1,+1], n)
    return np.cumsum(steps)
walk = random_walk(100)
print(walk)

[-1  0  1  0  1  0  1  2  3  4  5  4  3  2  1  2  3  4  3  4  5  4  3  4
  5  4  3  4  5  4  5  6  5  4  5  6  7  8  7  8  9 10  9 10  9  8  9 10
  9 10  9  8  7  8  9  8  7  8  7  6  7  8  7  6  5  4  5  6  5  4  3  2
  3  2  1  0 -1  0  1  0  1  2  1  2  3  4  3  4  5  6  5  4  3  4  3  4
  3  4  3  4]


In [25]:
def func(seq, sub):
    return [i for i in range(len(seq) - len(sub)) if seq[i:i+len(sub)] == sub]

In [30]:
func([1,2,3,10],[2,3])

[1]

In [31]:
def func2(seq, sub):
    target = np.dot(sub, sub)
    candidates = np.where(np.correlate(seq, sub, mode='valid') == target)[0]
    check = candidates[:, np.newaxis] + np.arange(len(sub))
    mask = np.all((np.take(seq, check) == sub), axis=-1)
    return candidates[mask]

In [32]:
func2([1,2,3,10],[2,3])

array([1])

In [33]:
Z = np.ones(4*1000000, np.float32)

In [58]:
Z = np.arange(27).reshape(3,3,3).astype(np.int16)
print(Z)
# Indexing done in reverse "z,y,x"
Z[2,1,0]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


21

In [50]:
Z.ndim

4

In [69]:
s = np.arange(9).reshape(3,3).astype(np.int16)
s

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int16)

In [54]:
ss = s[::2,::2]
ss

array([[0, 2],
       [6, 8]], dtype=int16)

In [72]:
# View and copies
Z = np.zeros(9)
Z_view = Z[:5]
Z_view[...] = 1
print(Z)

[1. 1. 1. 1. 1. 0. 0. 0. 0.]


In [62]:
Z = np.zeros(9)
Z_copy = Z[[0,1,2]]
Z_copy[...] = 1
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [68]:
np.reshape(np.arange(9),(3,3))


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [64]:
B.shape

(3, 3)

In [66]:

for i in np.ndindex(B.shape):
    print (i, B[i])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [67]:
np.ndindex(*shape) #An N-dimensional iterator object to index arrays.

NameError: name 'shape' is not defined

In [83]:
B.argmin()

0

In [81]:
a = np.index(B.max())

AttributeError: module 'numpy' has no attribute 'index'

In [78]:
a