In [17]:
import numpy as np

```python
np.zeros((3,6))
np.eye(3)
np.full(2,2)
np.reshape(np.arange(9),(3,3).astype(np.int16)
```

### Numpy is a linear algebra library
Arrays
    - Vectors (1D)
    - Matrices (2D)

### Making arrays

In [3]:
# Create a matrices
my_mat = [[1,2,3,], [4,5,6,], [7,8,9,], ]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# 2d array
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
# Linspace
np.linspace(1,5, 10)

array([ 1.        ,  1.44444444,  1.88888889,  2.33333333,  2.77777778,
        3.22222222,  3.66666667,  4.11111111,  4.55555556,  5.        ])

In [23]:
# Identity Matrix
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [26]:
# constant matrices
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [19]:
# random matrices
10*np.random.random((4,3))

array([[8.69821807, 2.42541466, 3.4777485 ],
       [9.38154709, 1.40874434, 0.02417116],
       [0.59017617, 0.98350846, 9.47176714],
       [1.75304802, 3.05143782, 8.42308185]])

In [20]:
# 10 random integers from 1-100
vec = np.random.randint(1,101, 10)
print(len(vec))
vec.max()

10


86

In [12]:
# min and max
mat = np.eye(4)
print(mat.max(), mat.min())

# Index location
print(mat.argmax())

1.0 0.0
0


In [43]:
# Check the shape
print(mat.shape)

# Check the datatype
print(mat.dtype)

(2, 5)
int64


In [12]:
new_arr = np.arange(50).reshape(5,10)
print(new_arr)

# Check the datatype
print(new_arr.dtype)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
int64


### Indexing and Operations

In [46]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
print(arr[8])
print(arr[1:5])
print(arr[5:])

8
[1 2 3 4]
[ 5  6  7  8  9 10]


In [55]:
# copy data
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
# Slicing is simply viewing, whereas "copy" is a deep copy that is independent of the original
arr_slice = arr[2:5]
arr_slice

array([2, 3, 4])

In [58]:
# If we change our slice we actually change the original

# set slice to 0
arr_slice[:] = 0

# view slice
print(arr_slice)

# view original
print(arr)

# view copy
print(arr_copy)

[0 0 0]
[ 0  1  0  0  0  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [61]:
# Indexing into matrices
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [70]:
# Double bracket [row][col]
print(arr_2d[1][2])

# Single bracket [,]
print(arr_2d[1,2])

30
30


In [72]:
# Grab top right corner with slice
# [rows 0-1, cols 1-2]
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [74]:
arr_2d[0:,2]

array([15, 30, 45])

In [85]:
# Conditional selection
bool_arr = arr_2d > 25

print("\nThis is the boolean array: \n", bool_arr)

print("\nThis is the matched arr_2d vs bool_arr: \n", arr_2d[bool_arr])

print("\nFast way \n ",arr_2d[arr_2d<20])


This is the boolean array: 
 [[False False False]
 [False False  True]
 [ True  True  True]]

This is the matched arr_2d vs bool_arr: 
 [30 35 40 45]

Fast way 
  [ 5 10 15]


### Array Operations

In [88]:
arr_2d ** 2


array([[  25,  100,  225],
       [ 400,  625,  900],
       [1225, 1600, 2025]])

In [89]:
np.sqrt(arr_2d)

array([[ 2.23606798,  3.16227766,  3.87298335],
       [ 4.47213595,  5.        ,  5.47722558],
       [ 5.91607978,  6.32455532,  6.70820393]])

In [90]:
np.exp(arr_2d)

array([[  1.48413159e+02,   2.20264658e+04,   3.26901737e+06],
       [  4.85165195e+08,   7.20048993e+10,   1.06864746e+13],
       [  1.58601345e+15,   2.35385267e+17,   3.49342711e+19]])

In [91]:
np.sin(arr_2d)

array([[-0.95892427, -0.54402111,  0.65028784],
       [ 0.91294525, -0.13235175, -0.98803162],
       [-0.42818267,  0.74511316,  0.85090352]])

In [92]:
np.log(arr_2d)

array([[ 1.60943791,  2.30258509,  2.7080502 ],
       [ 2.99573227,  3.21887582,  3.40119738],
       [ 3.55534806,  3.68887945,  3.80666249]])

In [97]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
arr = np.arange(0,1,0.01).reshape(10,10)
arr

array([[ 0.  ,  0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,
         0.09],
       [ 0.1 ,  0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,
         0.19],
       [ 0.2 ,  0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,
         0.29],
       [ 0.3 ,  0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,
         0.39],
       [ 0.4 ,  0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,
         0.49],
       [ 0.5 ,  0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,
         0.59],
       [ 0.6 ,  0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,
         0.69],
       [ 0.7 ,  0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,
         0.79],
       [ 0.8 ,  0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,
         0.89],
       [ 0.9 ,  0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,
         0.99]])

In [55]:
np.linspace(0,1, 20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [58]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [59]:
al = mat[2:,1:]
al

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [67]:
mat[3,4]


20

In [70]:
mat[0:3,1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [71]:
mat[4,:]

array([21, 22, 23, 24, 25])

In [72]:
mat[3,:]

array([16, 17, 18, 19, 20])

In [74]:
mat.sum()

325

In [77]:
# Two ways for standard deviation
print(np.std(mat))
print(mat.std())

7.21110255093
7.21110255093


In [81]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])